import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {
    MDBNavbar,
    MDBNavbarNav,
    MDBNavbarItem,
    MDBNavbarLink,
    MDBNavbarToggler,
    MDBContainer,
    MDBIcon
} from 'mdb-react-ui-kit';

export default function Home() {
    return (

        <div className={styles.container}>

            <header>
                <MDBNavbar expand='lg' light bgColor='white'>
                    <MDBContainer fluid>
                        <MDBNavbarToggler
                            aria-controls='navbarExample01'
                            aria-expanded='false'
                            aria-label='Toggle navigation'
                        >
                            <MDBIcon fas icon='bars' />
                        </MDBNavbarToggler>
                        <div className='collapse navbar-collapse' id='navbarExample01'>
                            <MDBNavbarNav right className='mb-2 mb-lg-0'>
                                <MDBNavbarItem active>
                                    <MDBNavbarLink aria-current='page' href='/'>
                                        Home
                                    </MDBNavbarLink>
                                </MDBNavbarItem>
                                <MDBNavbarItem>
                                    <MDBNavbarLink href='/press'>Press</MDBNavbarLink>
                                </MDBNavbarItem>
                                <MDBNavbarItem>
                                    <MDBNavbarLink href='/contact'>Contact us</MDBNavbarLink>
                                </MDBNavbarItem>
                                <MDBNavbarItem>
                                    <MDBNavbarLink href='/products'>Products</MDBNavbarLink>
                                </MDBNavbarItem>
                                <MDBNavbarItem>
                                    <MDBNavbarLink href='/donate'>Donate</MDBNavbarLink>
                                </MDBNavbarItem>
                            </MDBNavbarNav>
                        </div>
                    </MDBContainer>
                </MDBNavbar>
            </header>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
                      integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4"
                      crossOrigin="anonymous"/>
            </Head>

            <main className={styles.main}>
                
                    
                <h2 className={styles.semititle}>
                    About Us
                </h2>

                <p className={styles.description}>
                    BinaryHeart is a student organization whose objective 
                    is to <code className={styles.code}>spread Digital 
                    Access</code>. We collect donations of broken or 
                    used electronic devices and repair them. Through 
                    Northwestern Settlement and other partner charities, 
                    the devices are donated to help our less privileged 
                    peers. Our hope is that our work will lift people out 
                    of poverty, make higher education a reality for more 
                    students, and change lives.
                </p>       
                
                <div
                    className ={styles.static_card}
                    style={{
                        border: "1px solid #f57192",
                        "background-color": "rgb(255, 240, 243)"
                    }}
                >
                    <h1>
                        <center>We've done some cool stuff</center>
                    </h1>
                    <p className={styles.description}>
                        We have... donated to some cool places, including Kenya. Check out these pictures!
                        For our contributions, we won some cool awards too.
                    </p>
                    <div class={styles.grid}>

                        <img className={styles.scalingimage} src="/656348main_ToV_transit_diag_full.jpg" />

                        <p class={styles.description}>
                            asdf
                        </p>

                        <p class={styles.description}>
                            asdf
                        </p>

                        <p class={styles.description}>
                            asdf
                        </p>
                    </div>
                </div>
               
                <div className ={styles.static_card}>
                    <h1>
                        <center>Student Leaders</center>
                    </h1>

                    <p className={styles.description}>
                        <b> Maryanne Xu</b>
                         <p>Hi everyone! I’m a senior at New Trier High School.
                            I volunteered for BinaryHeart for four years.
                            During club meetings, I allocate tasks, run club logistics, and work on this website!
                             I can hold my breath for 2 hours.</p>
                        <b> Nicholas Sutherland</b>
                        <p> Howdy! I’m Nicholas, a senior at New Trier High School,
                            and this is my third year at BinaryHeart. I usually end up building shelves,
                            organizing screwdrivers, and working on our workspace during club.
                            Oh yeah, and I invented the microwave burrito.
                            .</p>
                        <b> Rom Fradkin</b>
                        <p> Rom Fradkin (5’ 9’’, 150lbs) is a senior at New Trier High School.
                            He’s volunteered for BinaryHeart since freshman year. He owns four cows.
                            .</p>
                        <b> Julia Hudson </b>
                        <p> Hey! I’m Julia, a sophomore at New Trier High School.
                            I’ve volunteered for BinaryHeart for two years now.
                            When not fixing computers, I work on our website,
                            manage our inventory system, and have plans for chapter expansion.
                            .</p>
                        <b> Andrew Gill </b>
                        <p> Hello, I’m Andrew! :) I’m a senior at New Trier High School,
                            and I’ve been in the club since my sophomore year.
                            I’m usually in charge of organization, whether on the task sheet or
                            in the closet I spent an entire year setting up.
                            By the way, I’ve been to the North Pole!
                            .</p>
                    </p>
                </div>

                <a href="/" className={styles.card}>
                     <h2>Back to the launch page &rarr;</h2>
                 </a>
            </main>



        </div>
    )
}
