import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <font color = "#ff0040">Binary</font><font color = "#193961">Heart</font>!
        </h1>
      
        <p className={styles.description}>
          BinaryHeart is an after-school nonprofit that repairs donated technology and re-donates those devices to low-income schools
          
          
        </p>

        <div className={styles.grid}>
          <a href="/products" className={styles.card}>
            <h2>Availabe Pruducts &rarr;</h2>
            <p>See the solutions we have to offer!</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Press &rarr;</h2>
            <p>See our press coverage in the news</p>
          </a>

          <a
            href="/about"
            className={styles.card}
          >
            <h2>About Us &rarr;</h2>
            <p>See our mission, what we've done, and who we are</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Contact Us &rarr;</h2>
            <p>
              Want to donate or recieve old technology? Get in contact!
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
